services:
  server:
    build: .
    image: kagurazakanyaa/ghidra-server:latest
    network_mode: bridge
    restart: unless-stopped
    ports:
      - 13100-13102:13100-13102/tcp
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/opt/ghidra/repositories
